spring.application.name=api
server.port=4000                                      
spring.datasource.url=jdbc:mysql://mysql-21b6b855-miapirest.g.aivencloud.com:20854/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update